class NodeData:
    DEPTH = 'depth'
    STATE = 'state'
    ACTION = 'action'
    REWARD = 'reward'
    VISIT = 'visit' 
    VALUE = 'value'
    VALUE_HISTORY = 'value_history'
    Trajectory = 'trajectory'
    NUMBER = 'number'
    TYPE = 'type'
    JOINTS = 'joints'
    LEVEL1 = 'level1'
    LEVEL2 = 'level2'
    SUCCESS = 'success'
    COST = 'cost'
    TEST = 'test'